const quotes = [
    "El verdadero crecimiento empieza cuando decides salir de tu zona de confort.",
    "Cada desafío es una oportunidad disfrazada de obstáculo.",
    "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.",
    "La perseverancia convierte los sueños en realidad.",
    "La creatividad no es un don, sino una habilidad que se cultiva con la práctica.",
    "El mayor riesgo es no tomar ninguno.",
    "El éxito no es el destino, sino el viaje.",
    "Tu actitud determina tu altitud.",
    "Cada día es una nueva página en tu historia, ¡escribe algo increíble!",
    "La fuerza de voluntad es el primer paso hacia cualquier logro significativo.",
    "La grandeza se construye a partir de pequeños pasos valientes.",
    "El único límite a tus sueños es el que tú te pongas.",
    "La magia sucede cuando te atreves a creer en ti mismo.",
    "El futuro pertenece a aquellos que actúan hoy.",
    "La pasión es el combustible que enciende el fuego del éxito.",
    "Cada error es un peldaño hacia el logro.",
    "El cambio es el primer paso hacia el progreso.",
    "La resiliencia es la clave para convertir los desafíos en oportunidades.",
    "El verdadero éxito se mide por la capacidad de inspirar a otros.",
    "Tu esfuerzo es el pincel que pinta tu destino.",
    "No temas al fracaso, teme a no intentarlo.",
    "Cada día es una oportunidad para reinventarte.",
    "La visión sin acción es solo un sueño.",
    "El crecimiento personal comienza con la voluntad de cambiar.",
    "La confianza en uno mismo es el primer secreto del éxito.",
    "El coraje es la puerta que abre todas las posibilidades.",
    "La disciplina es el puente entre tus metas y tus logros.",
    "La autenticidad es el primer paso hacia una vida plena.",
    "El éxito no se encuentra, se construye con cada decisión.",
    "La esperanza es el faro que guía el camino en tiempos de oscuridad.",
    "La grandeza comienza cuando decides ser valiente.",
    "Cada pequeño paso te acerca a tu objetivo.",
    "La creatividad no tiene límites, solo los que tú le pongas.",
    "Tu actitud es el reflejo de tus aspiraciones.",
    "El cambio empieza con un simple acto de voluntad.",
    "El éxito es un viaje, no un destino.",
    "Tu vida es un lienzo en blanco; pinta algo hermoso.",
    "El verdadero coraje es actuar a pesar del miedo.",
    "No subestimes el poder de un sueño.",
    "La perseverancia convierte los fracasos en logros.",
    "La verdadera fuerza se encuentra en la paciencia.",
    "No esperes a que las oportunidades lleguen; créalas.",
    "El momento perfecto es el que eliges hacer algo ahora.",
    "Cada desafío es una oportunidad para crecer.",
    "El esfuerzo de hoy es el éxito de mañana.",
    "Cada día es una nueva oportunidad para empezar de nuevo.",
    "La confianza en uno mismo es el primer paso hacia el éxito.",
    "La pasión y el esfuerzo pueden transformar cualquier sueño en realidad.",
    "El valor no es la ausencia de miedo, sino la decisión de enfrentarlo.",
    "La clave para el éxito es empezar antes de estar listo.",
    "Cada acción cuenta en la búsqueda de tus metas.",
    "El futuro pertenece a aquellos que crean su propio destino.",
    "La autenticidad es la mayor forma de poder.",
    "La vida es una aventura; no tengas miedo de explorarla.",
    "El éxito es el resultado de la preparación, el trabajo duro y aprender del fracaso.",
    "Cada pequeño avance cuenta en el camino hacia tus sueños.",
    "No dejes que los miedos te detengan; usa tu valentía para avanzar.",
    "Los sueños no tienen fecha de caducidad.",
    "La mente es un campo fértil; siembra pensamientos positivos.",
    "La actitud positiva es la clave para abrir puertas.",
    "Los grandes logros comienzan con pequeños pasos.",
    "No te conformes con lo que tienes; aspira a lo que puedes ser.",
    "La vida es un reflejo de tus pensamientos; manténlos positivos.",
    "El éxito no es un accidente; es el resultado de la dedicación y el trabajo.",
    "Cada error es una lección valiosa en el camino hacia el éxito.",
    "La única forma de hacer un trabajo extraordinario es amar lo que haces.",
    "Tu potencial es ilimitado; no dejes que las dudas te detengan.",
    "La verdadera felicidad se encuentra en el proceso, no en el resultado.",
    "La confianza en ti mismo es tu mayor activo.",
    "Cada día es una nueva oportunidad para alcanzar tus metas.",
    "El crecimiento personal comienza con la decisión de cambiar.",
    "El viaje hacia el éxito es tan importante como el destino final.",
    "La actitud positiva es la clave para superar cualquier obstáculo."
];

const quote = document.getElementById('quote');
const display = document.getElementById('display');

const generateQuote = () => {
    let randomQuote = Math.floor(Math.random() * quotes.length);
    quote.textContent = quotes[randomQuote];
}

display.addEventListener('click', generateQuote);


